language: node_js

node_js:
  - "10"

dist: xenial

cache: npm

services:
  - docker

script:
  - export VERSION=`cat $TRAVIS_BUILD_DIR/package.json | jq -r '.version'`
  - export DOCKER_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $VERSION; else echo $VERSION-$TRAVIS_BRANCH-r1; fi`
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -t ratehub/openfaas-kafka-connector:$DOCKER_TAG .
  - docker push ratehub/openfaas-kafka-connector
  - if ([[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]);
      then
        docker tag ratehub/openfaas-kafka-connector:$DOCKER_TAG ratehub/openfaas-kafka-connector:latest;
        docker push ratehub/openfaas-kafka-connector:latest;
    fi
