# Default values for openfaas-kafka-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: ratehub/openfaas-kafka-connector:latest
connector_name: openfaas-kafka-connector
gateway_uri: gateway.openfaas:8080
gateway_ssl: false
topics: test-stream-1,mortgage-application-dev
kafka_connection: ratehub-kafka-ratehub-094c.aivencloud.com:21424
kafka_ssl: true
redis_connection: 127.0.0.1
redis_ssl: false
redis_port: 6379

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
